
version: "3"
services:
  mongo:
    image: mongo:4.2.9
    container_name: forrich_mongo
    restart: always
  server:
    image: forrich_server:latest
    container_name: forrich_server
    restart: always
    ports:
      - 9000:9000